name: CI

on:
 push:
   branches: [ main ]
 pull_request:
   branches:
   - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: abhinavsingh/setup-bazel@v3
      - name: Setup Bazel
        uses: ./
      - name: Bazel Build
        if: matrix.os != 'windows'
        run: bazel build //...
      - name: Bazel Test
        run: bazel test //...
